version: "3.8"
services:
  calendar:
    build:
      context: ..
      dockerfile: build/Dockerfile
    depends_on:
      rabbitmq3:
         condition: service_started
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: otus
      POSTGRES_USER: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 30s
      timeout: 60s
      retries: 5
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    ports:
      - "5050:80"

  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - '5672:5672'