version: "3.1"
services:
  calendar:
    build:
      context: ..
      dockerfile: build/Dockerfile
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: otus
      POSTGRES_USER: postgres
    depends_on:
      - calendar
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    ports:
      - "5050:80"

  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - '5672:5672'