version: "3.8"
services:
  calendar:
    build:
      context: ..
      dockerfile: build/calendar/Dockerfile
    depends_on:
      migration:
         condition: service_started
      rabbitmq3:
         condition: service_started
      db:
        condition: service_healthy
    ports:
      - "2022:2022"
      - "8888:8888"
  migration:
    build:
      context: ..
      dockerfile: build/migrations/Dockerfile
    depends_on:
      db:
        condition: service_healthy
  scheduler:
    build:
      context: ..
      dockerfile: build/scheduler/Dockerfile
    depends_on:
      rabbitmq3:
        condition: service_started
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: otus
      POSTGRES_USER: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 30s
      timeout: 60s
      retries: 5
    ports:
      - "5432:5432"
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - '5672:5672'