logger:
  level: DEBUG
  development: True
  logfile: ~/log

httpserver:
  host: 127.0.0.1
  port: 2021

grpcserver:
  host: 127.0.0.1
  port: 2022
  available: true

storage:
  dsn:  postgres://postgres:PASSWORD@db/otus?sslmode=disable

queue:
  dsn: amqp://myuser:mypassword@localhost:5672